# Generated by Django 6.0.4 on 2026-09-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBoxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashboxes.cashbox')),
            ],
        ),
    ]
