# Generated by Django 6.0.4 on 2026-04-17 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0003_purchasepayment'),
        ('sales', '0005_alter_salespayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('repeat_type', models.CharField(choices=[('weekly', 'Weekly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('next_reminder_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('repeat_type', models.CharField(choices=[('weekly', 'Weekly')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminder_date', models.DateField(blank=True, null=True)),
                ('next_reminder_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesinvoice')),
            ],
        ),
    ]
