# Generated by Django 6.0.4 on 2026-04-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit_cost_syp', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total_syp', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
