# Generated by Django 6.0.4 on 2026-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseinvoice_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='line_total_syp',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='line_total_usd',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_cost_syp',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
