# Generated by Django 6.0.4 on 2026-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_remove_purchaseinvoiceitem_line_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10),
        ),
    ]
