# Generated by Django 6.0.4 on 2026-04-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchasepayment_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceitem',
            options={'verbose_name': 'Invoice Item', 'verbose_name_plural': 'Invoice Items'},
        ),
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
