# Generated by Django 6.0.4 on 2026-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='exchange_rate_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
