# Generated by Django 6.0.4 on 2026-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchaseinvoice_exchange_rate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
