# Generated by Django 6.0.4 on 2026-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_purchaseinvoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_cost_syp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
