# Generated by Django 6.0.4 on 2026-05-21 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_purchaseinvoiceitem_unit_cost_syp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
