# Generated by Django 6.0.4 on 2026-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_purchaseinvoice_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'verbose_name': 'Purchase Payment', 'verbose_name_plural': 'Purchase Payments'},
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10),
            preserve_default=False,
        ),
    ]
