# Generated by Django 6.0.4 on 2026-09-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_alter_purchasepayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='payment_method',
        ),
    ]
