# Generated by Django 6.0.4 on 2026-04-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='warehouse',
        ),
    ]
