# Generated by Django 6.0.4 on 2026-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0002_damage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
