# Generated by Django 6.0.4 on 2026-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
