# Generated by Django 6.0.4 on 2026-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20),
        ),
    ]
