# Generated by Django 6.0.4 on 2026-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='operation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('damage', 'Damage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
