# Generated by Django 6.0.4 on 2026-04-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='movement_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
