# Generated by Django 6.0.4 on 2026-04-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_movement_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='movement_qty',
        ),
    ]
