# Generated by Django 6.0.4 on 2026-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
