# Generated by Django 6.0.4 on 2026-04-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_remove_branch_warehouse'),
        ('warehouses', '0002_warehouse_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
