# Generated by Django 6.0.4 on 2026-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10),
        ),
    ]
