# Generated by Django 6.0.4 on 2026-04-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesinvoice_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='line_total_syp',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='line_total_usd',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='unit_price',
        ),
    ]
