# Generated by Django 6.0.4 on 2026-05-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_salesinvoiceitem_line_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salesinvoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
