# Generated by Django 6.0.4 on 2026-05-17 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesinvoice_exchange_rate_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='salespayment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payment'},
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='sales.salesrepresentative'),
        ),
    ]
