# Generated by Django 6.0.4 on 2026-05-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
