# Generated by Django 6.0.4 on 2026-05-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesrepresentative_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespayment',
            name='payment_method',
        ),
    ]
