# Generated by Django 6.0.4 on 2026-09-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0002_cashboxtransaction'),
        ('sales', '0011_remove_salespayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='cashboxes.cashbox'),
        ),
    ]
