# Generated by Django 6.0.4 on 2026-09-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0002_cashboxtransaction'),
        ('sales', '0012_salesinvoice_cash_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='cash_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payments', to='cashboxes.cashbox'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
